title: Hello C
description: C 程序设计基础课程资料。
url: https://www.labafan.cc
baseurl: /hello-c
markdown: kramdown
defaults:
  - scope:
      path: ""
    values:
      layout: default
      nav: true
      order: 1000
      listing: true
  - scope:
      path: environment
    values:
      section: environment
      nav: false
  - scope:
      path: materials
    values:
      section: materials
      nav: false
  - scope:
      path: qa
    values:
      section: qa
      nav: false
  - scope:
      path: beyond
    values:
      section: beyond
      nav: false
exclude: [README.md]
